"""Known Feel24 gyms."""

from __future__ import annotations

# Source: https://feel24.no/treningssentre
# Last synchronized: 2026-08-20
GYMS: tuple[str, ...] = (
    "Feel24 Alstad",
    "Feel24 Alta Bossekop",
    "Feel24 Alta Kronstad",
    "Feel24 Alta Nordlysbadet",
    "Feel24 Alta Parksenteret",
    "Feel24 Andenes",
    "Feel24 Ankenes",
    "Feel24 Asker Langenga",
    "Feel24 Balanse",
    "Feel24 Bardu",
    "Feel24 Bardufoss",
    "Feel24 Beitostølen",
    "Feel24 Billingstad",
    "Feel24 Bjerkvik",
    "Feel24 Bodø Mørkved",
    "Feel24 Bodø Olav V",
    "Feel24 Bodø Performance",
    "Feel24 Bodø Sentrum",
    "Feel24 Bodø Tverlandet",
    "Feel24 Bodø Vestbyen",
    "Feel24 Borkenes",
    "Feel24 Brobekk Vollebekk",
    "Feel24 Brumunddal",
    "Feel24 Brygga",
    "Feel24 Buran",
    "Feel24 Byåsen",
    "Feel24 Dalgård",
    "Feel24 Eidkjosen",
    "Feel24 Elverum",
    "Feel24 Fauske",
    "Feel24 Finnsnes",
    "Feel24 Fornebu",
    "Feel24 Gamlebyen Panorama",
    "Feel24 Gard Senter",
    "Feel24 Grorud Senter",
    "Feel24 Hagan",
    "Feel24 Hammerfest",
    "Feel24 Harstad Grottebadet",
    "Feel24 Harstad Medkila",
    "Feel24 Harstad Sama",
    "Feel24 Harstad Seljestad",
    "Feel24 Harstad Sentrum",
    "Feel24 Haugesund Sentrum",
    "Feel24 Heggedal",
    "Feel24 Heimdal",
    "Feel24 Hokksund",
    "Feel24 Høvik",
    "Feel24 Ilsvika",
    "Feel24 Kirkenes",
    "Feel24 Krokstadelva",
    "Feel24 Leknes",
    "Feel24 Levanger",
    "Feel24 Lien",
    "Feel24 Lommedalen",
    "Feel24 Lyngen",
    "Feel24 Melbu",
    "Feel24 Misvær",
    "Feel24 Mo Amfi",
    "Feel24 Mo Gruben",
    "Feel24 Mo Ytteren",
    "Feel24 Molde",
    "Feel24 Mosjøen",
    "Feel24 Myre",
    "Feel24 Myrvoll",
    "Feel24 Narvik Sentrum",
    "Feel24 Nordkjosbotn",
    "Feel24 Oppegård",
    "Feel24 Oppsal",
    "Feel24 Risvollan",
    "Feel24 Rognan",
    "Feel24 Rotnes",
    "Feel24 Rælingen",
    "Feel24 Rønvika",
    "Feel24 Salhus",
    "Feel24 Sandnessjøen",
    "Feel24 Sandnessjøen Lyngåsen",
    "Feel24 Skjervøy",
    "Feel24 Skjetten",
    "Feel24 Skytta Gjelleråsen",
    "Feel24 Skåla",
    "Feel24 Slemmestad",
    "Feel24 Sortland Kjøpmannsgata",
    "Feel24 Sortland Rådhusgata",
    "Feel24 Stamsund",
    "Feel24 Steinkjer",
    "Feel24 Stjørdal",
    "Feel24 Stokmarknes Sentrum",
    "Feel24 Stokmarknes Søndre",
    "Feel24 Stormyra Panorama",
    "Feel24 Strømmen",
    "Feel24 Sulitjelma",
    "Feel24 Svolvær Panorama",
    "Feel24 Svolvær Sentrum",
    "Feel24 Sørreisa",
    "Feel24 Tangen",
    "Feel24 Tolvsrød",
    "Feel24 Tranby",
    "Feel24 Tromsø Fagereng",
    "Feel24 Tromsø Fløylia",
    "Feel24 Tromsø Håpet",
    "Feel24 Tromsø Isrenna",
    "Feel24 Tromsø Skippergata",
    "Feel24 Tromsø Sportssenter",
    "Feel24 Tromsø Strandgata",
    "Feel24 Tromsø The Box",
    "Feel24 Tromsø Tomasjord",
    "Feel24 Tromsø Treningssenter",
    "Feel24 Tromsø Tromsdalen",
    "Feel24 Tyholttårnet",
    "Feel24 Vadsø",
    "Feel24 Valnesfjorden",
    "Feel24 Verdal",
    "Feel24 Vollen",
    "Feel24 Vøyenenga",
    "Feel24 Økern Brobekk",
    "Feel24 Øren",
)

_GYMS_BY_NORMALIZED_NAME = {gym.casefold(): gym for gym in GYMS}


def resolve_gym(value: str | None) -> str | None:
    """Return the canonical gym name, an empty string, or None if unknown."""
    normalized = " ".join((value or "").split())
    if not normalized:
        return ""
    return _GYMS_BY_NORMALIZED_NAME.get(normalized.casefold())


def select_effective_gym(fixed_gym: str, chosen_gym: str) -> str:
    """Return the fixed gym, or the runtime choice when no gym is fixed."""
    return fixed_gym or chosen_gym
